# Generated by Django 3.1.7 on 2021-03-26 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetails',
            fields=[
                ('campID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=100, validators=[django.core.validators.MinValueValidator(2, 'Address must be longer than 2 characters')])),
                ('OrgName', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2, 'Organisation name must be longer than 2 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donorID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2, 'The first name must be longer than 2 characters')])),
                ('lastName', models.CharField(max_length=50)),
                ('bloodVariety', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100, validators=[django.core.validators.MinValueValidator(2, 'Address must be longer than 2 characters')])),
                ('email', models.EmailField(max_length=20)),
                ('phoneNumber', models.IntegerField(max_length=15)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2, 'The first name must be longer than 2 characters')])),
                ('lastName', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100, validators=[django.core.validators.MinValueValidator(2, 'Address must be longer than 2 characters')])),
                ('email', models.EmailField(max_length=20)),
                ('phoneNumber', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('donationID', models.AutoField(primary_key=True, serialize=False)),
                ('campID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.campdetails')),
                ('donorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donor')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.worker')),
            ],
        ),
    ]
